[tool.bumpversion]
current_version = "0.3.0"
tag = true
commit = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
