---
# UPDATE: `pre-commit autoupdate`
default_language_version:
  python: python3.11
exclude: "secrets.yml$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # Generall Stuff
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      # VCS
      - id: check-merge-conflict
      # Config / Data Files
      - id: check-yaml
      - id: check-toml
      # Python
      - id: debug-statements
      - id: requirements-txt-fixer
  # Prettier (HTML, JS, CSS, Markdown…)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: ".*\\.(ya?ml|py)$"
  # Python: check syntax via flakehell
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: "flake8"
  # Python: reorder imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --force-single-line-imports
  # Python: lint with black
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
