name: Test Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          make setup
      - name: Build and install package
        run: |
          make build
          make install
      - name: Run tests
        run: |
          make test
